
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN COMMA COMMENT DATETIME DOT EQUALS KEY LCHAVETA LPAREN LSQBRACKET NEWLINE NUMBER RCHAVETA RPAREN RSQBRACKET STRING\n    toml : contents\n    \n    contents : content\n            | content NEWLINE contents\n    \n    content : table \n           | variable\n    \n    table : LSQBRACKET KEY RSQBRACKET NEWLINE table_contents\n          | LSQBRACKET KEY DOT KEY RSQBRACKET NEWLINE table_contents\n    \n    table : LSQBRACKET KEY RSQBRACKET NEWLINE\n          | LSQBRACKET KEY DOT KEY RSQBRACKET NEWLINE\n    \n    table_contents : variable\n                   | variable table_contents\n    \n    variable : KEY EQUALS value\n             | KEY EQUALS value NEWLINE\n    \n    value : STRING\n          | BOOLEAN\n          | NUMBER\n          | DATETIME\n          | list\n    \n    list : LSQBRACKET RSQBRACKET\n         | LSQBRACKET list_values RSQBRACKET\n    \n    list_values : value\n                 | value COMMA list_values\n                 | value COMMA NEWLINE list_values\n    '
    
_lr_action_items = {'LSQBRACKET':([0,8,10,20,31,35,],[6,6,20,20,20,20,]),'KEY':([0,6,8,13,14,15,16,17,18,19,21,23,24,28,30,33,],[7,9,7,22,-12,-14,-15,-16,-17,-18,7,-13,-19,7,-20,7,]),'$end':([1,2,3,4,5,11,14,15,16,17,18,19,21,23,24,27,28,30,32,33,36,],[0,-1,-2,-4,-5,-3,-12,-14,-15,-16,-17,-18,-8,-13,-19,-6,-10,-20,-11,-9,-7,]),'NEWLINE':([3,4,5,12,14,15,16,17,18,19,21,23,24,27,28,29,30,31,32,33,36,],[8,-4,-5,21,23,-14,-15,-16,-17,-18,-8,-13,-19,-6,-10,33,-20,35,-11,-9,-7,]),'EQUALS':([7,],[10,]),'RSQBRACKET':([9,15,16,17,18,19,20,22,24,25,26,30,34,37,],[12,-14,-15,-16,-17,-18,24,29,-19,30,-21,-20,-22,-23,]),'DOT':([9,],[13,]),'STRING':([10,20,31,35,],[15,15,15,15,]),'BOOLEAN':([10,20,31,35,],[16,16,16,16,]),'NUMBER':([10,20,31,35,],[17,17,17,17,]),'DATETIME':([10,20,31,35,],[18,18,18,18,]),'COMMA':([15,16,17,18,19,24,26,30,],[-14,-15,-16,-17,-18,-19,31,-20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'toml':([0,],[1,]),'contents':([0,8,],[2,11,]),'content':([0,8,],[3,3,]),'table':([0,8,],[4,4,]),'variable':([0,8,21,28,33,],[5,5,28,28,28,]),'value':([10,20,31,35,],[14,26,26,26,]),'list':([10,20,31,35,],[19,19,19,19,]),'list_values':([20,31,35,],[25,34,37,]),'table_contents':([21,28,33,],[27,32,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> toml","S'",1,None,None,None),
  ('toml -> contents','toml',1,'p_toml','TP_yacc.py',8),
  ('contents -> content','contents',1,'p_contents','TP_yacc.py',16),
  ('contents -> content NEWLINE contents','contents',3,'p_contents','TP_yacc.py',17),
  ('content -> table','content',1,'p_content','TP_yacc.py',26),
  ('content -> variable','content',1,'p_content','TP_yacc.py',27),
  ('table -> LSQBRACKET KEY RSQBRACKET NEWLINE table_contents','table',5,'p_table','TP_yacc.py',33),
  ('table -> LSQBRACKET KEY DOT KEY RSQBRACKET NEWLINE table_contents','table',7,'p_table','TP_yacc.py',34),
  ('table -> LSQBRACKET KEY RSQBRACKET NEWLINE','table',4,'p_table_empty','TP_yacc.py',43),
  ('table -> LSQBRACKET KEY DOT KEY RSQBRACKET NEWLINE','table',6,'p_table_empty','TP_yacc.py',44),
  ('table_contents -> variable','table_contents',1,'p_table_contents','TP_yacc.py',53),
  ('table_contents -> variable table_contents','table_contents',2,'p_table_contents','TP_yacc.py',54),
  ('variable -> KEY EQUALS value','variable',3,'p_variable','TP_yacc.py',66),
  ('variable -> KEY EQUALS value NEWLINE','variable',4,'p_variable','TP_yacc.py',67),
  ('value -> STRING','value',1,'p_value','TP_yacc.py',76),
  ('value -> BOOLEAN','value',1,'p_value','TP_yacc.py',77),
  ('value -> NUMBER','value',1,'p_value','TP_yacc.py',78),
  ('value -> DATETIME','value',1,'p_value','TP_yacc.py',79),
  ('value -> list','value',1,'p_value','TP_yacc.py',80),
  ('list -> LSQBRACKET RSQBRACKET','list',2,'p_list','TP_yacc.py',86),
  ('list -> LSQBRACKET list_values RSQBRACKET','list',3,'p_list','TP_yacc.py',87),
  ('list_values -> value','list_values',1,'p_list_values','TP_yacc.py',96),
  ('list_values -> value COMMA list_values','list_values',3,'p_list_values','TP_yacc.py',97),
  ('list_values -> value COMMA NEWLINE list_values','list_values',4,'p_list_values','TP_yacc.py',98),
]
